apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-blog-config
  namespace: flask-blog
data:
  FLASK_ENV: production
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"
  SQLALCHEMY_DATABASE_URI: "sqlite:////app/flaskblog/data/site.db"
