apiVersion: v1
kind: Secret
metadata:
  name: flask-blog-secrets
  namespace: flask-blog
type: Opaque
data:
  SECRET_KEY: <base64 encoded secret key>
  EMAIL_USER: <base64 encoded email user>
  EMAIL_PASS: <base64 encoded email password (App password)>
